git:
  submodules: true
language: scala
# run on new infrastructure
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin
    CHISEL_TESTERS=1.5.+

install:
  # Install dependencies
  - bash .install_verilator.sh
  - verilator --version

script:
  - set -o pipefail && sbt -Dchisel-iotestersVersion=$CHISEL_TESTERS test

